Repository mojohaus/tidy-maven-plugin, pull requests merged in 2022-09, with the labels that each got.

#56 Bump mojo-parent from 65 to 70
  pom.xml
Labels: dependencies

#62 Project cleanup
  pom.xml
  src/site/markdown/index.md
  src/site/markdown/usage.md.vm
  src/site/site.xml
Labels: enhancement

#63 Add dependabot configuration
  .github/dependabot.yml
Labels: build

#69 Cleanup dependencies in tests
  src/test/resources/org/codehaus/mojo/tidy/task/complete-pom/pom-expected.xml
  src/test/resources/org/codehaus/mojo/tidy/task/complete-pom/pom.xml
Labels: maintenance

#70 Cleanup dependencies in it tests
  src/it/pom/pom-expected.xml
  src/it/pom/pom.xml
Labels: maintenance

#71 Execute checkstyle during build and apply recommended code format
  pom.xml
  src/main/java/org/codehaus/mojo/tidy/CheckMojo.java
  src/main/java/org/codehaus/mojo/tidy/TidyMojo.java
  src/main/java/org/codehaus/mojo/tidy/task/EnsureOrderAndIndent.java
  src/test/java/org/codehaus/mojo/tidy/task/PomTidyFixesTest.java
  src/test/java/org/codehaus/mojo/tidy/task/PomTidyTest.java
Labels: maintenance
